# Generated by Django 5.2.1 on 2025-05-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='Panagarh', max_length=100),
            preserve_default=False,
        ),
    ]
