# Generated by Django 5.2.1 on 2025-05-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments',
            field=models.TextField(default='Nothing to show', max_length=300),
        ),
    ]
